kumuluzee:
  name: tt-orders
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/OrdersDS
      connection-url: jdbc:postgresql://127.0.0.1:5431/order
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/OrdersDS

  metrics:
   web-instrumentation:
   - name: orders-endpoint
   url-pattern: /v1/order/*

rest-properties:
  healthy: true
  external-services:
    menu-service:
      enabled: true