apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - image: tabletopltd/tt-orders
        name: orders
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-orders:5432/order
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://localhost:32696
          - name: KUMULUZEE_DISCOVERY
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 25
          periodSeconds: 10
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP
